// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdklbqcisqvwjryggvcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdka2xicWNpc3F2d2pyeWdndmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODA4NTEsImV4cCI6MjA3MzU1Njg1MX0.llGCh71Ojs_3E3Mhaxh3AautOoUqNhUsKkfni6zqNwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});